# ==============================================================
# WAX CONFIGURATION
# ==============================================================
# Jekyll configuration files are written in YAML format.
# Colons, tabs/spacing, and quotes are meaningful in YAML.
# It is recommended you look at the following guide to avoid
# syntax errors in this file:
# ~> https://learnxinyminutes.com/docs/yaml/
#
#
# Questions ?
# ~> https://minicomp.github.io/wiki/#/
# ~> https://gitter.im/minicomp/wax/
#
# ---------------------------------------------------------------
# MAIN SETTINGS
# ---------------------------------------------------------------
# Feel free to change these! For more info, refer to:
# ~> https://jekyllrb.com/docs/configuration/options/

title:            'laislat'
description:      'test site for laislab'
url:              'https://github.com/binipringle.io'
baseurl:          '/laislat'
copyright:        '(c) 2020 Sabina Pringle with a Creative Commons Attribution-NonCommercial-ShareAlike-4.0 International license (CC BY-NC-SA 4.0)'
logo:             '/assets/logo.png'

# ---------------------------------------------------------------
# BUILD SETTINGS
# ---------------------------------------------------------------
# Best not to mess with these unless you know what you're doing!

permalink: 'pretty'
sass:
  style: compressed
exclude:
  - Gemfile*
  - Rakefile
  - vendor
  - spec
  - README.md
webrick:
  headers:
    'Access-Control-Allow-Origin': '*'
kramdown:
 auto_ids:       true
 footnote_nr:    1
 entity_output:  as_char
 footnote_backlink: "&#x21a9;&#xfe0e;"
 toc_levels:     1..6
 smart_quotes:   lsquo,rsquo,ldquo,rdquo
 enable_coderay: false


# --------------------------------------------------------------
# COLLECTION SETTINGS
# --------------------------------------------------------------
# Wax leverages Jekyll collections for much of its
# functionality, therefor some of the keys below are from
# Jekyll while others are Wax-specific.
# For more info, refer to:
# ~> https://jekyllrb.com/docs/collections/

collections:
  exhibits:
    output: true
  laislab: # name of collection
    output: true # makes sure pages are output as html files
    layout: 'laislab_item' # the layout for the pages to use
    metadata:
      source: 'laislab.csv' # path to the metadata file within `_data`
    images:
      source: 'raw_images/laislab' # path to the directory of images within `_data`
  graffitti: # name of collection
    output: true # makes sure pages are output as html files
    layout: 'graffitti_item' # the layout for the pages to use
    metadata:
      source: 'graffitti.csv' # path to the metadata file within `_data`
    images:
      source: 'raw_images/graffitti' # path to the directory of images within `_data`
  pig: # name of collection
    output: true # makes sure pages are output as html files
    layout: 'pig_item' # the layout for the pages to use
    metadata:
      source: 'pig.csv' # path to the metadata file within `_data`
    images:
      source: 'raw_images/pig' # path to the directory of images within `_data`

# --------------------------------------------------------------
# SEARCH INDEX SETTINGS
# --------------------------------------------------------------
# You can create multiple search indexes below (though only one is
# recommended!) by specifying
# an `index` file to write it to and some `collections` for it to index
# and running `$ bundle exec rake wax:search` .

search:
  main:
    index: '/search/index.json' # file the index will get written to
    collections:
      laislab:
        content: false # whether or not to index page content
        fields: # the metadata fields to index
          - artist
          - location
          - label
          - _date
          - object_type
          - current_location

# --------------------------------------------------------------
# SITE MENU SETTINGS
# --------------------------------------------------------------
# Each menu item needs a `label` (whats shown), and a `link`
# (where it goes). An item can optionally have a dropdown
# submenu via `sub`.

menu:
  - label: 'About'
    sub:
      - label: 'laislab'
        link: '/about/'
      - label: 'Documentation'
        link: 'https://github.com/binipringle/laislat'
      - label: 'Credits'
        link: '/credits/'
  - label: 'Exhibits'
    sub:
      - label: 'Inline Parallax Image'
        link: '/exhibits/a/'
      - label: 'Inline Image References'
        link: '/exhibits/b/'
      - label: 'Inline Parallax Image 2'
        link: '/exhibits/c/'
      - label: 'Inline Image References 2'
        link: '/exhibits/d/'
      - label: 'Inline Image References 3'
        link: '/exhibits/e/'
  - label: 'Browse'
    link: '/collection/'
  - label: 'Search'
    link: '/search/'
  - label: 'Reuse'
    link: '/reuse/'

# --------------------------------------------------------------
# SITE FOOTER SETTINGS
# --------------------------------------------------------------
#

footer:
  links:
    - label: 'GitHub'
      link: 'https://github.com/binipringle/laislat'
    - label: 'Credits'
      link: '/credits'
    - label: 'Contact'
      link: 'https://vimeo.com/user11490981'
  logos:
    - img: '/img/logo.png'

# FIN
